name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Run tests
        run: |
          php artisan test
          test_result=$?
          if [ $test_result -ne 0 ]; then
            echo "Tests failed. Exiting..."
            exit $test_result
          fi

      - name: Deploy using ssh
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/laravel_ci_cd
            git pull origin master
