name: Deploy

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/laravel_ci_cd
            git pull origin master
            git status
