name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create View & Session Directory
        run: mkdir -p storage/framework/{views,sessions,cache}

      - name: Install dependencies
        run: composer install > dev/null 2>&1

      # Copy .env.example to .env
      - name: Copy .env.example to .env
        run: cp .env.example .env

      # Generate the Application Key
      - name: Generate Application Key
        run: php artisan key:generate

      - name: Application Cache Clear
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: Run tests
        run: |
          php artisan test
          test_result=$?
          if [ $test_result -ne 0 ]; then
            echo "Tests failed. Exiting..."
            exit $test_result
          fi

      - name: Deploy using ssh
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/laravel_ci_cd
            git pull origin master > /dev/null 2>&1
            composer update > /dev/null 2>&1
            php artisan migrate
            php artisan optimize:clear
