name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      COMPOSER_VERSION: 2.7.1
      PHP_VERSION: 8.1
      DB_DATABASE: laravel_ci_cd
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ""

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create View & Session Directory
        run: mkdir -p storage/framework/{views,sessions,cache}

      - name: Get composer cache directory
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: install

      # Copy .env.example to .env
      - name: Copy .env.example to .env
        run: cp .env.example .env

      # Generate the Application Key
      - name: Generate Application Key
        run: php artisan key:generate

      - name: Application Cache Clear
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: Run tests
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: |
          php artisan test
          test_result=$?
          if [ $test_result -ne 0 ]; then
            echo "Tests failed. Exiting..."
            exit $test_result
          fi

      - name: Deploy using ssh
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/laravel_ci_cd
            git pull origin master
            composer update
            php artisan migrate
            php artisan optimize:clear
